from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QLabel, QVBoxLayout, QHBoxLayout, QMessageBox, QRadioButton
from random import randint
app=QApplication([])
main_win=QWidget()
main_win.show()
main_win.setWindowTitle('Испытай удачу, друг!')
main_win.move(900, 70)
main_win.resize(400,200)
but1=QPushButton('1')
but2=QPushButton('2')
but3=QPushButton('3')
but4=QPushButton('4')
but5=QPushButton('5')
layoutH1=QHBoxLayout()
layoutH2=QHBoxLayout()
layoutH3=QHBoxLayout()
layoutH1.addWidget(but1,alignment=Qt.AlignLeft)
layoutH1.addWidget(but2,alignment=Qt.AlignRight)
layoutH2.addWidget(but3,alignment=Qt.AlignCenter)
layoutH3.addWidget(but4,alignment=Qt.AlignLeft)
layoutH3.addWidget(but5,alignment=Qt.AlignRight)
layout_main=QVBoxLayout()
layout_main.addLayout(layoutH1)
layout_main.addLayout(layoutH2)
layout_main.addLayout(layoutH3)
main_win.setLayout(layout_main)
app.exec_()